import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"], // Bebas Neue only has 400, but you can leave it explicit
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebas.variable} font-sans antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
